<a href="https://colab.research.google.com/github/AL-DN/Welcome_to_Numpy/blob/main/NumpyNotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Reference:** https://www.youtube.com/watch?v=QUT1VHiLmmI

Load Numpy (pip i numpy)

In [ ]:
import numpy as np

# **Create** `numpy array` by **passing in a list**

In [ ]:
# 1D
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D
b = np.array([[9.9,8.8,7.7],[5.5,6.6,7.7]])
print(b)

[[9.9 8.8 7.7]
 [5.5 6.6 7.7]]


# You can view the dimension of NumpyArr

In [ ]:
print("The NumpyArr A has {} dimensions".format(a.ndim))
print("The NumpyArr B has {} dimensions".format(b.ndim))

The NumpyArr A has 1 dimensions
The NumpyArr B has 2 dimensions


# You can find the size of the array (rows,colums)

In [ ]:
# when it is 1D it will return # of elements
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

# You can view Data Type

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

# We can also specify this when creating NumpyArr


*   This is useful to save memory and decrease runtime if data size is known to be under a certain value






In [ ]:
c = np.array([4,5,6],dtype='int16')

# We can view size of Array in multiple capactities



**Returns size of each item in bytes**

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

8

In [ ]:
c.itemsize

2

**Returns total number of items in Array**

In [ ]:
a.size

3

In [ ]:
b.size

6

In [ ]:
c.size

3

Size of Entire Array in Bytes
(itemsize * size)

In [ ]:
a.nbytes

24

# Accessing/Changing specific elements, rows, colums, etc

In [ ]:
test = np.array([[1,2,3,4,5,6,7],
                 [8,9,10,11,12,13,14]])

**Get specific element**
by using numpy_array[row,column]
* negative indexing works too

In [ ]:
test[1,5]

13

**Get a specific row/column**
* slice tool grabs all row or column values

In [ ]:
test[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
test[:,2]

array([ 3, 10])

**Getting more fancy**
[start:end:stepsize]

In [ ]:
test[0, 0:test.size:2]

array([1, 3, 5, 7])

You can **change** values by simply accessing their 'coordinate'

In [ ]:
test[0,2] = 5
# Take another look at even indexs on row 0
test[0, 0:test.size:2]

array([1, 5, 5, 7])

**You can also use slice to replace all values on r/c**

In [ ]:
test[0,:] = 5
# Take another look at even indexs on row 0
test[0, 0:test.size:2]

array([5, 5, 5, 5])